backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
#publish_mode: editorial_workflow
media_folder: "uploads" 
site_url: https://pustakasaga.com/
display_url: https://pustakasaga.com/
collections:
  - name: "home"
    label: "Home"
    files:
      - label: "Homepage"
        name: "home"
        file: "content/home/subheader.md"
        fields: 
          - {label: "Type", name: "type", widget: "hidden", default: "subheader"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "terbitan"
    label: "Terbitan"
    folder: "content/terbitan"
    create: true 
    sort: "date:desc"
    sortable_fields: ['title', 'date']
    slug: "{{slug}}" 
    summary: "{{title}}"
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "PDF"
        name: "pdf"
        widget: "file"
        media_library:
          media_folder: "/static/files"
          config:
            multiple: false
      - {label: "Publish Date", name: "date", widget: "datetime",date_format: "DD.MM.YYYY",time_format: "HH:mm"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "halaman"
    label: "Halaman"
    folder: "content"
    create: true 
    sort: "date:desc"
    sortable_fields: ['title', 'date']
    slug: "{{slug}}" 
    summary: "{{title}}"
    fields: 
      - {label: "Menu", name: "menu", widget: "hidden", default: "main", required: false}
      - {label: "Type", name: "type", widget: "hidden", default: "about"}
      - {label: "Wight", name: "weight", widget: "hidden", default: "10", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
